# PlacekeyRails Configuration
# Generated by PlacekeyRails install generator

# Set up the API client with your Placekey API key
<% if options[:api_key].present? %>
# SECURITY NOTE: Storing API keys directly in code is not recommended for production.
# Consider using Rails credentials or environment variables instead.
PlacekeyRails.setup_client("<%= options[:api_key] %>")
<% elsif options[:use_dotenv] %>
# Using dotenv for API key management
# Make sure you have dotenv-rails gem installed and PLACEKEY_API_KEY in your .env file
PlacekeyRails.setup_client(ENV["PLACEKEY_API_KEY"])
<% else %>
# Using Rails credentials for secure API key storage
# Add your key to credentials with: rails credentials:edit
# Format:
# placekey:
#   api_key: your_key_here
PlacekeyRails.setup_client(Rails.application.credentials.dig(:placekey, :api_key))
<% end %>

# Enable caching to improve performance (recommended)
PlacekeyRails.enable_caching(max_size: 1000)

# Configure other options
PlacekeyRails.configure do |config|
  # Default country code for address lookups
  config[:default_country_code] = "US"
  
  # Validate placekeys on assignment (recommended)
  config[:validate_placekeys] = true
  
  # API request timeout in seconds
  config[:api_timeout] = 10
  
  # Whether to raise exceptions on API errors
  config[:raise_on_api_error] = false
end
