# PlacekeyRails Configuration
# Generated by PlacekeyRails install generator

# Set up the API client with your Placekey API key
<% if options[:api_key].present? %>
PlacekeyRails.setup_client("<%= options[:api_key] %>")
<% else %>
# PlacekeyRails.setup_client("YOUR_API_KEY")
# You can get an API key from https://placekey.io
<% end %>

# Enable caching to improve performance (recommended)
PlacekeyRails.enable_caching(max_size: 1000)

# Configure other options
PlacekeyRails.configure do |config|
  # Default country code for address lookups
  config[:default_country_code] = "US"
  
  # Validate placekeys on assignment (recommended)
  config[:validate_placekeys] = true
  
  # API request timeout in seconds
  config[:api_timeout] = 10
  
  # Whether to raise exceptions on API errors
  config[:raise_on_api_error] = false
end
